import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.CellBiologyCellMembraneStructureTheoremCanonicalLaneLean.MembraneStructureBridgeLemmas
import HautevilleHouse.CellBiologyCellMembraneStructureTheoremCanonicalLaneLean.MembraneStructureGateLemmas

namespace HautevilleHouse
namespace CellBiologyCellMembraneStructureTheoremCanonicalLaneLean

def ConstrainedCellMembraneClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_cell_membrane_endgame (A : AdmissibleClass) : ConstrainedCellMembraneClosure A :=
  And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end CellBiologyCellMembraneStructureTheoremCanonicalLaneLean
end HautevilleHouse